In [1]:
import numpy as np

In [2]:
x = np.array(12)
x

array(12)

In [3]:
x.ndim

0

In [4]:
x.shape

()

In [5]:
x.size

1

In [6]:
y = np.array([1, 2, 3])
y

array([1, 2, 3])

In [7]:
y.ndim

1

In [8]:
y.shape

(3,)

In [9]:
y.size

3

In [10]:
z = np.array([[1, 2, 3, 4],
              [5, 6, 7 ,8],
              [9, 10, 11, 12]])
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
z.ndim

2

In [12]:
z.shape

(3, 4)

In [13]:
z.size

12

In [14]:
u = np.array([[[1, 2, 3],
               [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                 [16, 17, 18]],
                 [[19, 20, 21],
                  [22, 23, 24]]])
u

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [15]:
u.ndim

3

In [16]:
u.shape

(4, 2, 3)

In [17]:
u.size

24

In [18]:
u[0,0,0:3].shape

(3,)

In [19]:
a = [0, 1, 2, 3, 4, 5]
a[2:-1]

[2, 3, 4]

In [21]:
import tensorflow as tf

class NaiveDense:
    def __init__(self, input_size, output_size, activation) -> None:
        self.activation = activation

        w_shape = (input_size, output_size)
        w_initial_value = tf.random.uniform(w_shape, minval = 0, maxval=0.1)
        self.W = tf.Variable(w_initial_value)

        b_shape = (output_size, )
        b_initial_value = tf.zeros(b_shape)
        self.b = tf.Variable(b_initial_value)

    def __call__(self, inputs):
        return self.activation(tf.matmul(inputs, self.W) + self.b)
    
    @property
    def weights(self):
        return [self.W, self.b]

In [22]:
from typing import Any


class NaiveSequential:
    def __init__(self, layers) -> None:
        self.layers = layers
    
    def __call__(self, inputs) -> Any:
        x = inputs
        for layer in self.layers:
            x = layer(x)
        return x
    
    @property
    def weights(self):
        weights = []
        for layer in self.layers:
            weights += layer.weights
        return weights

In [24]:
model = NaiveSequential([
    NaiveDense(input_size=28 * 28, output_size=512, activation=tf.nn.relu),
    NaiveDense(input_size=512, output_size=10, activation=tf.nn.softmax)
])
assert len(model.weights) == 4

In [ ]:
import math

class BatchGenerator:
    def __init__(self) -> None:
        pass