In [25]:
import tensorflow as tf
import numpy as np

np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [5]:
x = tf.zeros(shape=(3,2))
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [8]:
x = tf.Variable(initial_value=3.0)
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [12]:
t = tf.Variable(0.0)
with tf.GradientTape() as tape2:
    with tf.GradientTape() as tape1:
        s = 4.9 * t * t
    v = tape1.gradient(s, t)
a = tape2.gradient(v, t)

a

<tf.Tensor: shape=(), dtype=float32, numpy=9.8>

In [153]:
n_train = 1000
n_features = 5

signal_spread = 5
noise_spread = 1

w_train = tf.random.uniform(shape=(n_features, 1), minval=-signal_spread, maxval=signal_spread)
b_train = tf.random.uniform(shape=(1,), minval=-signal_spread, maxval=signal_spread)

x_train = tf.random.uniform(shape=(n_train, n_features), minval=-signal_spread, maxval=signal_spread)
y_train = tf.matmul(x_train, w_train) + b_train + tf.random.normal(shape=(n_train, 1), mean=0, stddev=noise_spread)
y_train = tf.sigmoid(y_train)
y_train = tf.cast(y_train > 0.5, tf.float32)

In [154]:
w = tf.Variable(tf.random.uniform(shape=(n_features, 1), minval=0, maxval=0.1))
b = tf.Variable(tf.zeros(1))

def loss(y, p):
    l = -tf.reduce_mean(y * tf.math.log(p + 1e-16) + (1 - y) * tf.math.log(1 - p + 1e-16))
    return l

n_epochs = 1000
learning_rate = 1

for i in range(n_epochs):
    with tf.GradientTape() as tape:
        predict = tf.sigmoid(tf.matmul(x_train, w) + b)
        c = loss(y_train, predict)
        if (i + 1) % (n_epochs / 10) == 0:
            print(f'Epoch {i}: cost={c}')
    dw, db = tape.gradient(c, (w, b))
    w.assign_sub(learning_rate * dw)
    b.assign_sub(learning_rate * db)

predict = tf.cast(tf.sigmoid(tf.matmul(x_train, w) + b) > 0.5, tf.float32)
print(tf.reduce_mean(tf.abs(y_train - predict)))


Epoch 99: cost=0.06730528175830841
Epoch 199: cost=0.05774107202887535
Epoch 299: cost=0.05373676121234894
Epoch 399: cost=0.051511961966753006
Epoch 499: cost=0.05010151490569115
Epoch 599: cost=0.049135055392980576
Epoch 699: cost=0.04843779280781746
Epoch 799: cost=0.04791591316461563
Epoch 899: cost=0.04751436784863472
Epoch 999: cost=0.04719872400164604
tf.Tensor(0.019, shape=(), dtype=float32)


In [147]:
print(w_train / w)

tf.Tensor(15.0, shape=(), dtype=float32)
tf.Tensor(
[[0.911]
 [0.922]
 [0.883]
 [0.89 ]
 [0.9  ]], shape=(5, 1), dtype=float32)


In [156]:
n_features = 2
num_samples_per_class = 1000

neg_samples = np.random.multivariate_normal(
    mean=[0, 3],
    cov=[[1, 0.5],
         [0.5, 1]],
    size=num_samples_per_class)

pos_samples = np.random.multivariate_normal(
    mean=[3, 0],
    cov=[[1, 0.5],
         [0.5, 1]],
    size=num_samples_per_class
)

x_train = np.vstack((neg_samples, pos_samples)).astype(np.float32)
y_train = np.vstack((np.zeros((num_samples_per_class, 1), dtype=np.float32), np.ones((num_samples_per_class, 1), dtype=np.float32)))


In [157]:
input_dim = 2
output_dim = 1

w = tf.Variable(initial_value = tf.random.uniform(shape=(input_dim, output_dim)))
b = tf.Variable(initial_value= tf.zeros(shape=(output_dim,)))

def model(x_train):
    return tf.matmul(x_train, w) + b

def sq_loss(y_train, predict):
    return tf.reduce_mean(tf.square(y_train - predict))

learning_rate = 0.1
def training_step(x_train, y_train):
    with tf.GradientTape() as tape:
        predict = model(x_train)
        loss = sq_loss(y_train, predict)
    dw, db = tape.gradient(loss, (w, b))
    w.assign_sub(learning_rate * dw)
    b.assign_sub(learning_rate * db)
    return loss

for step in range(40):
    loss = training_step(x_train, y_train)
    print(f'Step {step}: loss={loss:.4f}')

Step 0: loss=3.3710
Step 1: loss=0.4219
Step 2: loss=0.1664
Step 3: loss=0.1185
Step 4: loss=0.1049
Step 5: loss=0.0973
Step 6: loss=0.0912
Step 7: loss=0.0857
Step 8: loss=0.0807
Step 9: loss=0.0761
Step 10: loss=0.0719
Step 11: loss=0.0681
Step 12: loss=0.0645
Step 13: loss=0.0612
Step 14: loss=0.0583
Step 15: loss=0.0555
Step 16: loss=0.0530
Step 17: loss=0.0507
Step 18: loss=0.0486
Step 19: loss=0.0466
Step 20: loss=0.0449
Step 21: loss=0.0432
Step 22: loss=0.0417
Step 23: loss=0.0403
Step 24: loss=0.0391
Step 25: loss=0.0379
Step 26: loss=0.0368
Step 27: loss=0.0359
Step 28: loss=0.0350
Step 29: loss=0.0341
Step 30: loss=0.0334
Step 31: loss=0.0327
Step 32: loss=0.0321
Step 33: loss=0.0315
Step 34: loss=0.0309
Step 35: loss=0.0305
Step 36: loss=0.0300
Step 37: loss=0.0296
Step 38: loss=0.0292
Step 39: loss=0.0289
